In [2]:
#neural network
import numpy as np
import pandas as pd


In [20]:
data = np.array([
    [25, 28.5, 80, 120, 0],
    [30, 33.2, 85, 130, 1],
    [45, 35.1, 90, 140, 1],
    [22, 26.7, 75, 110, 0],
    [50, 31.3, 88, 150, 1],
    [29, 29.0, 82, 125, 0],
    [40, 34.5, 89, 135, 1],
    [35, 30.2, 78, 128, 0],
    [60, 36.5, 95, 160, 1],
    [38, 27.8, 83, 118, 0]
])
x=data[:,:-1]
y=data[:,-1]
x=x.T
print(x)

[[ 25.   30.   45.   22.   50.   29.   40.   35.   60.   38. ]
 [ 28.5  33.2  35.1  26.7  31.3  29.   34.5  30.2  36.5  27.8]
 [ 80.   85.   90.   75.   88.   82.   89.   78.   95.   83. ]
 [120.  130.  140.  110.  150.  125.  135.  128.  160.  118. ]]


In [4]:
n=x.shape[0]
m=x.shape[1]
print(x.shape[0])

num_layers=2
num_neurons1=5
num_neurons2=1

# np.random.seed(42)
w_1=np.random.rand(num_neurons1,n)
w_2=np.random.rand(num_neurons2,num_neurons1)

b1=np.zeros((num_neurons1,1))
b2=np.zeros((num_neurons2,1))
print(w_1.shape)

4
(5, 4)


In [5]:
class activation:

    def relu(x):
        if x>0:
            return x
        else:
            return 0

    def sigmoid(z):
        y=1/(1+np.exp(-z))
        return y

In [6]:
def forward(w,x,b,activation):
    z=np.dot(w,x)+b
    a=activation(z)
    return a,z


In [7]:
a1,z1=forward(w_1,x,b1,activation.sigmoid)
print(a1,z1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] [[ 93.09126158 101.99747658 116.6640372   86.27252522 117.47275626
   97.60756927 112.29746561  98.59868706 131.42981527 103.8131707 ]
 [135.96081539 147.38640416 158.24687273 125.76048183 162.37460085
  140.74929643 153.94080797 141.17793815 175.39828858 136.7850904 ]
 [ 65.89528551  74.38017315  89.4435241   60.00907377  94.39837084
   70.567234    84.02685268  76.16519352 106.98507664  75.16681921]
 [ 44.17318223  48.9944974   56.17955574  40.47000842  58.84743389
   46.63109708  53.49551883  48.89079783  65.36729411  47.61865726]
 [ 58.67774348  66.21308449  77.37699101  54.16634776  77.16811409
   61.88997485  73.8492492   64.8322299   88.3792791   66.21287192]]


In [8]:
a2,z2=forward(w_2,z1,b2,activation.sigmoid)
print(a2,z2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] [[144.4229381  160.12070465 182.40828662 133.14381296 185.97415046
  151.65632595 174.82032736 156.72482134 207.95940345 156.81689778]]


In [15]:
def compute_cost(y,y_hat):
    l=y*np.log(y_hat)+(1-y)*np.log(1-y_hat)
    j=np.sum(l)
    return j

In [24]:
def gradient_descent(num_iters, alpha):
    global w_1, w_2, b1, b2 ,y # If weights are defined outside
    
    for i in range(num_iters):
        # FORWARD PASS
        a1, z1 = forward(w_1, x, b1,activation.sigmoid)
        a2, z2 = forward(w_2, a1, b2,activation.sigmoid)

        # BACKWARD PASS
        m = x.shape[1]  # assuming x is (n_features, m_samples)
        
        dz2 = a2 - y  # derivative of loss wrt z2 (for sigmoid + MSE)
        dw2 = (1/m) * np.dot(dz2, a1.T)
        db2 = (1/m) * np.sum(dz2, axis=1, keepdims=True)

        # sigmoid'(z1) = a1 * (1 - a1)
        dz1 = np.dot(w_2.T, dz2) * (a1 * (1 - a1))
        dw1 = (1/m) * np.dot(dz1, x.T)
        db1 = (1/m) * np.sum(dz1, axis=1, keepdims=True)

        # PARAMETER UPDATE
        w_1 = w_1 - alpha * dw1
        w_2 = w_2 - alpha * dw2
        b1 = b1 - alpha * db1
        b2 = b2 - alpha * db2

        if (i%100==0):
            cost=compute_cost(y,a2)
            print(f"cost at iteration {i}:{cost}")


In [25]:
gradient_descent(num_iters=10000,alpha=0.01)

cost at iteration 0:-6.931471805599453
cost at iteration 100:-6.931471805599453
cost at iteration 200:-6.931471805599453
cost at iteration 300:-6.931471805599453
cost at iteration 400:-6.931471805599453
cost at iteration 500:-6.931471805599453
cost at iteration 600:-6.931471805599453
cost at iteration 700:-6.931471805599453
cost at iteration 800:-6.931471805599453
cost at iteration 900:-6.931471805599453
cost at iteration 1000:-6.931471805599453
cost at iteration 1100:-6.931471805599453
cost at iteration 1200:-6.931471805599453
cost at iteration 1300:-6.931471805599453
cost at iteration 1400:-6.931471805599453
cost at iteration 1500:-6.931471805599453
cost at iteration 1600:-6.931471805599453
cost at iteration 1700:-6.931471805599453
cost at iteration 1800:-6.931471805599453
cost at iteration 1900:-6.931471805599453
cost at iteration 2000:-6.931471805599453
cost at iteration 2100:-6.931471805599453
cost at iteration 2200:-6.931471805599453
cost at iteration 2300:-6.931471805599453
cost